### ISSUE TITLE
Plutip - `CannotFindTimeInEraSummaries`

### ISSUE THREAD

**Issue by codybutz** [Plutonomicon/cardano-transaction-lib#1057] opened 2022-09-20 20:39 UTC
Hello!

I am experiencing an error when trying to balance a TX against the Plutip environment that has a UpperBound on the validity range.

```
Error: (CannotConvertPOSIXTimeRange (Interval { from: (LowerBound NegInf true), to: (UpperBound (Finite (POSIXTime (fromString "1663706074400"))) true) }) (CannotFindTimeInEraSummaries (AbsTime (fromString "190400"))))
```

You can find an example of the code here: https://github.com/codybutz/ctl-examples/tree/plutip-posix-time-error and can be tested with: `nix build .#checks.x86_64-linux.ctl-scaffold-plutip-test -L`

I'm unsure honestly at the root cause of this error, however I have a slight feeling it has something to do with the faster slots being used by in the Plutip environment.

**Comment by klntsky** [comment] 2022-09-21 09:59
Thanks for reporting!
This is a problem with Plutip we are aware of.

**Comment by klntsky** [comment] 2022-09-21 10:00
The root cause is that eraSummaries are ill-formed.

**Comment by klntsky** [comment] 2022-12-20 11:30
Update:
They are no more ill-formed, they just span too short into the future. It's possible to change `PlutipConfig`'s `slotLength` now

**Comment by KristianBalaj** [comment] 2023-03-01 18:55
@klntsky 
Just to refresh this issue, we're still experiencing that error.
However, we have a workaround - setting the `epochSize` here https://github.com/Plutonomicon/cardano-transaction-lib/blob/205f25b591656b825186d2187fdcba1e00c3df87/src/Internal/Plutip/Server.purs#L410
The default value seems to be 80 seconds, when we override it with `432000` (same as mainnet, the problem goes away).

**Comment by klntsky** [comment] 2023-10-05 10:35
Setting `epochSize` is a valid fix for this problem.

**Closed by klntsky** 2023-10-05 10:35 UTC
Labels: bug, critical, plutip
