### ISSUE TITLE
Extra datum with simple Ada transfer

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#340] opened 2022-04-22 06:49 UTC
Attempting to submit the transaction in `examples/Pkh2Pkh.purs` results in:

```
{
  "type": "jsonwsp/response",
  "version": "1.0",
  "servicename": "ogmios",
  "methodname": "SubmitTx",
  "result": {
    "SubmitFail": [
      {
        "extraDataMismatch": {
          "provided": "6c5f384a73bacc120b6b78c55d1078d0e422898b75b5434127ba028479747347",
          "inferredFromParameters": null
        }
      }
    ]
  },
  "reflection": { "id": "SubmitTx-l29wf6qu", "step": "INIT" }
}
```
Avoiding `finalizeTx` entirely solves this, but that is not a good solution

**Comment by adamczykm** [comment] 2022-04-26 15:23
Will try to tackle it now. I'd appreciate any hints.

**Comment by adamczykm** [comment] 2022-04-27 01:37
It seems that indeed server's transaction finalization adds extra scriptdatahash.

Before finalization:
```purescript
(Transaction { auxiliaryData: Nothing, body: (TxBody { auxiliaryDataHash: Nothing, certs: Nothing, collateral: (Just [(TransactionInput { index: 0u, transactionId: (TransactionHash (byteArrayFromIntArrayUnsafe [135,219,43,11,252,36,57,93,220,202,232,206,36,193,199,138,27,104,156,125,186,143,139,219,225,192,171,72,76,53,15,39])) })]), fee: (Coin fromString "868185"), inputs: [(TransactionInput { index: 0u, transactionId: (TransactionHash (byteArrayFromIntArrayUnsafe [192,18,44,107,209,144,3,155,129,193,153,151,205,55,153,146,202,70,132,186,188,104,210,193,167,160,196,160,180,223,56,250])) })], mint: Nothing, networkId: (Just TestnetId), outputs: [(TransactionOutput { address: (Address addr_test1qqedq7jjt5h26dl4czzlhv2k050nhuple9349q33jk6dkps69vqzk0ux2gq7xayz9nx3gfkzsqmw74jpcqvwvt9mnycqf39du9), amount: (Value (Coin fromString "991122438") (NonAdaAsset(fromFoldable []))), dataHash: Nothing }),(TransactionOutput { address: (Address addr_test1vqedq7jjt5h26dl4czzlhv2k050nhuple9349q33jk6dkpskpqzss), amount: (Value (Coin fromString "2000000") (NonAdaAsset(fromFoldable []))), dataHash: Nothing })], requiredSigners: Nothing, scriptDataHash: Nothing, ttl: Nothing, update: Nothing, validityStartInterval: Nothing, withdrawals: Nothing }), isValid: true, witnessSet: (TransactionWitnessSet { bootstraps: Nothing, nativeScripts: Nothing, plutusData: Nothing, plutusScripts: Nothing, redeemers: Nothing, vkeys: Nothing }) })
```
After finalization
```purescript
(Transaction { auxiliaryData: Nothing, body: (TxBody { auxiliaryDataHash: Nothing, certs: Nothing, collateral: (Just [(TransactionInput { index: 0u, transactionId: (TransactionHash (byteArrayFromIntArrayUnsafe [135,219,43,11,252,36,57,93,220,202,232,206,36,193,199,138,27,104,156,125,186,143,139,219,225,192,171,72,76,53,15,39])) })]), fee: (Coin fromString "868185"), inputs: [(TransactionInput { index: 0u, transactionId: (TransactionHash (byteArrayFromIntArrayUnsafe [192,18,44,107,209,144,3,155,129,193,153,151,205,55,153,146,202,70,132,186,188,104,210,193,167,160,196,160,180,223,56,250])) })], mint: Nothing, networkId: (Just TestnetId), outputs: [(TransactionOutput { address: (Address addr_test1qqedq7jjt5h26dl4czzlhv2k050nhuple9349q33jk6dkps69vqzk0ux2gq7xayz9nx3gfkzsqmw74jpcqvwvt9mnycqf39du9), amount: (Value (Coin fromString "991122438") (NonAdaAsset(fromFoldable []))), dataHash: Nothing }),(TransactionOutput { address: (Address addr_test1vqedq7jjt5h26dl4czzlhv2k050nhuple9349q33jk6dkpskpqzss), amount: (Value (Coin fromString "2000000") (NonAdaAsset(fromFoldable []))), dataHash: Nothing })], requiredSigners: Nothing, scriptDataHash: (Just (ScriptDataHash (byteArrayFromIntArrayUnsafe [108,95,56,74,115,186,204,18,11,107,120,197,93,16,120,208,228,34,137,139,117,181,67,65,39,186,2,132,121,116,115,71]))), ttl: Nothing, update: Nothing, validityStartInterval: Nothing, withdrawals: Nothing }), isValid: true, witnessSet: (TransactionWitnessSet { bootstraps: Nothing, nativeScripts: Nothing, plutusData: Nothing, plutusScripts: Nothing, redeemers: Nothing, vkeys: Nothing }) })
```

**Comment by ngua** [comment] 2022-04-27 04:00
@adamczykm Nice find, I imagine that's the issue

**Comment by adamczykm** [comment] 2022-04-28 17:59
I was working with Peter on this. And we've found the root cause:

`hashScriptIntegrity` that the server uses to add the integrity hash uses:
>     Datums
>     Redeemers
>     A set of "languages" (either PlutusV1 or PlutusV2)
> 
> It returns SNothing if all of the above are null (for some notion of null, not totally sure which), or a hash if not.The CTL server was hardcoding languages = Set.fromList [PlutusV1] , but since it was a PKH2PKH transaction, it was (apparently) meant to be languages = Set.fromList []. We've confirmed that this fixes it for the PKH2PKH transaction, but:
> 
>     the logic about when this is meant to return Nothing  isn't documented. Our best guess is that if the transaction has no scripts attached, it should be Nothing, and should be a hash otherwise
>     Because of this, we're not positive whether our "fix" is truly a fix, or if it just works around the issue.
> 

If anyone here happens to know how can I confirm it please let me know. I intend to implement the mentioned fix.

**Comment by ngua** [comment] 2022-05-04 04:30
Also copying @adamczykm's message from the CTL discord for visibility here:

>@dragospe  and I have found the root cause behind pkh2pkh txs being rejected. It boils down to:
```
  let languages = Set.fromList [PlutusV1]
      txDatums =
        TxWitness.TxDats . Map.fromList $
          decodedDatums <&> \datum -> (Data.hashData datum, datum)
      mbIntegrityHash =
        Tx.hashScriptIntegrity
          (C.toLedgerPParams C.ShelleyBasedEraAlonzo pparams)
          mempty
          decodedRedeemers
          txDatums
```

>during transaction finalization on CTL's server. The set of languages is hard-coded even if there are no script being involved in a transaction. Setting it to mempty in such case resolves the issue.
>Whereas the node does this:
```
  let languages = languages @era tx utxo
```

>Would following the node logic be a good solution here? Can anyone confirm it? The node code is under-documented or I wasn't able to find any comments on this.

**Comment by Luis-omega** [comment] 2022-05-10 19:52
It seems that #395 is a good fix for this since we have in https://hydra.iohk.io/build/14336174/download/1/alonzo-changes.pdf on page 5 : 

```
All transactions also need to supply a redeemer for all items that are validated by a script ... Note that
 the same script could be used for multiple different purposes in the same transaction, 
 so in general it might be necessary to include more than one
 redeemer per script. There will, however, always be at least one redeemer per script.
```

It only remains to check if this is also true for minting policies.

I understand that minting policies begin in `Mary era` ( https://hydra.iohk.io/build/14336372/download/1/shelley-ma.pdf page 4)  but I still haven't found if this was replaced with plutusV1 or if it still remains as part of `phase 1`.

**Comment by Luis-omega** [comment] 2022-05-10 20:30
I also opened #397 implementing the discussed solution in slack.

**Closed** 2022-05-11 07:17 UTC
Labels: bug, haskell server, stage 4
