### ISSUE TITLE
Rework `getWalletCollateral` to support KeyWallet

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#510] opened 2022-06-07 16:13 UTC
As part of #437, `balanceTx` handles adding wallet collateral in an ad-hoc fashion for each wallet. We could investigate modifying `QueryM.getWalletCollateral` to handle those cases by adding the parameters needed by `KeyWallet`'s `selectCollateral` to it. Alternatively, we make `getWalletCollateral` clear that it's for CIP30 wallets.

Actually, I noticed in CIP30 that it specifies the `getCollateral` function should take an amount parameter, which would be useful for `selectCollateral` in `KeyWallet` too. However, it's hard to tell how one can calculate the required collateral before balancing

**Comment by klntsky** [comment] 2022-06-07 19:38
I have two ideas:

- We may use a separate type here, something like `CollateralizedKeyWallet`, with a smart constructor consisting of sending a collateral Tx. But the problem is that the wallet must be provided before `Contract` is interpreted, but sending a Tx is a `Contract` action. FAIL
- We can delegate creation of `KeyWallet`s to [`PlutipM` monad interpreter](https://github.com/Plutonomicon/cardano-transaction-lib/pull/470/files#diff-230fb24d0be65335bfd35ee9f246fb2b1a205c7cb09a95eb0eda2a12655fd24aR69). It can just request one extra UTXO from plutip-server on initialization and provide a pre-funded `KeyWallet` with collateral already set.

**Comment by ngua** [comment] 2022-08-10 06:42
Closed by #860

**Closed by ngua** 2022-08-10 06:42 UTC
